"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/Authproviders";
import Navbar from "@/Component/Navbar/Navbar";
import Footer from "@/Component/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <div className="min-h-screen flex flex-col justify-between">
            <AuthProvider>
            {children}
            </AuthProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
